config/routes.rb
Rails.application.routes.draw do
  get 'books/available'
  get 'books/reserved'
  get 'books/bought'

  root 'books#available'

  get 'get_book/:book_id', to: 'books#get_book', as: 'get_book'
  get 'change_state_book/:book_id/:new_state', to: 'books#change_state_book', as: 'change_state_book'
  delete 'delete/:book_id', to: 'books#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def available
    @books= Book.where(state: 0)
  end

  def reserved
    @books= Book.where(state: 1)
  end

  def bought
    @books= Book.where(state: 2)
  end

  def get_book
    @book = Book.find(params[:book_id])
    respond_to do |format|
      format.js
    end
  end

  def change_state_book
    @mensaje = ''
    @book = Book.find(params[:book_id])
    original_state = @book.state

    if original_state == 0
      sleep 3
    end

    if params[:new_state] == "2" && (Time.now.utc - @book.updated_at.utc).to_i > 10
      @mensaje = 'El tiempo de reserva se agoto'
    else
      @book.state = params[:new_state]
      @book.save
    end
  
    @books = Book.where(state: original_state)

    respond_to do |format|
      format.js
    end
  end

  def destroy
    @book = Book.find(params[:book_id])
    if @book.destroy
      redirect_to books_bought_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div class="book_card border m-1 p-3">
    
    <% if book.state == 0 %>
        <span class="badge badge-primary">Disponible</span>
    <% elsif book.state == 1 %>
        <span class="badge badge-warning">Reservado</span>
    <% else %>
        <span class="badge badge-success">Pagado</span>
    <% end%>

    <h3>
        <%= book.title %>
    </h3>

    <p><%= book.description %></p>
    <%= link_to "VER MAS", get_book_path(book), remote: true, class: 'btn btn-info'%>

    <% if book.state == 0 %>
        <%= link_to "Reservar", change_state_book_path(book.id, 1),remote: true,data: {disable_with: "Procesando reserva..."}, class: 'btn btn-secondary'%>
    <% elsif book.state == 1 %>
        <%= link_to "Pagar", change_state_book_path( book.id, 2), remote: true, class: 'btn btn-warning'%>
        <%= link_to "Eliminar Reserva", change_state_book_path( book.id, 0), remote: true, class: 'btn btn-danger'%>
    <% else %>
        <%= link_to "Eliminar", destroy_book_path(book), method: :delete, data: {confirm: "Esta seguro de eliminar el registro?", disable_with: "Eliminando registro de compra..."}, remote: true, class: 'btn btn-danger'%>
    <% end%>

</div>

app/views/books/available.html.erb
<h1>Books#available</h1>
<p>Find me in app/views/books/available.html.erb</p>

<div class="books_list">
    <%= render @books %>
</div>

<div class="modal fade" id="verMasModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="verMasModalTitle">Titulo</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
    </div>
  </div>
</div>

app/views/books/bought.html.erb
<h1>Books#bought</h1>
<p>Find me in app/views/books/bought.html.erb</p>

<div class="books_list">
    <%= render @books %>
</div>

app/views/books/change_state_book.js.erb
<% if @mensaje != '' %>    
    alert("<%= @mensaje %>")
<% else %>

    <% if @book.state == 1 %>
        alert("Libro Reservado!!");
    <% elsif @book.state == 2 %>
        alert("Libro Pagado!!");
    <% else %>
        alert("Libro Eliminado!!");  
    <% end %>

<% end %>

$(".books_list").html("");
$(".books_list").html("<%= j render @books %>");

app/views/books/get_book.js.erb
$("#verMasModalTitle").html("<%= @book.title %>");
$(".modal-body").html("<%= j @book.description%>");
$("#verMasModal").modal("show");

app/views/books/reserved.html.erb
<h1>Books#reserved</h1>
<p>Find me in app/views/books/reserved.html.erb</p>

<div class="books_list">
    <%= render @books %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Libros</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div>
        <%= link_to 'Disponibles', books_available_path, class: "btn btn-primary" %>
        <%= link_to 'Reservados', books_reserved_path, class: "btn btn-warning" %>
        <%= link_to 'Comprados', books_bought_path, class: "btn btn-success" %>
      </div>
      <%= yield %>
    </div>
    


    <script src="https://code.jquery.com/jquery-3.5.1.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" ></script>
  </body>
</html>